### PR TITLE
Transformed trend plot to scatter with rolling mean and enabled multiple country selection

### LINKED ISSUE #84: Maybe select multiple countries to compare trends?

### PR DESCRIPTION
**Pull request by meretelutz**
Closes #84 and #68

### CODE REVIEW

**Comment by killerninja8** [comment]
Hey @meretelutz, looks great! I'm having trouble seeing the "TOP 15 COUNTRIES OF POLLUTANT" and "TREND OF POLLUTANT OVER TIME" plots. 

I'm not sure if it's an issue with my laptop or if there's a code change to be made.

**Comment by meretelutz** [comment]
Hey! Ok I think it might be that you don't have a package installed, can you run this line in the environment before you try again?

`conda install vl-convert-python`

**Comment by meretelutz** [comment]
But also before anyone merges this commit, let me change the plot really quick!

**Comment by meretelutz** [comment]
Ok now should be ready to merge!

**Comment by killerninja8** [comment]
Oh, that’s probably the case. Since it’s working for you, I’ll go ahead and
merge as soon as I’m home. I’ll also install this package to avoid any
issues in the future. Thanks!

*Siddharth Grover*
Student | Master of Data Science @ UBC

**Comment by carinaya** [comment]
For the multiple countries filter, I have some concern about this, since we wanna the country filter to reflect the selection of the filters at the top, and we set the default, if the default is exluded from the option, there will be an error...

**Comment by carinaya** [comment]
@meretelutz And I download the package you mention, the line chart and bar chart  does not show on my computer. In terms of the issue I mention above, you might refer my code in the  https://github.com/UBC-MDS/DSCI-532_2024_2_pollution-tracker/pull/100, we can use a call back to set the default as the first or first two countries.

**Comment by meretelutz** [comment]
> For the multiple countries filter, I have some concern about this, since we wanna the country filter to reflect the selection of the filters at the top, and we set the default, if the default is exluded from the option, there will be an error...

Good point! Hadn't thought of that! I'll check out your code and make adjustments.

**Comment by meretelutz** [comment]
Huh, not sure why its not showing up for you guys. I just ran it all again and it was looking fine. All I can think of is the environment file, but if anyone has any other ideas let me know. 

This is what its supposed to look like: 
Screenshot 2024-04-12 at 10 19 15 PM

**Comment by carinaya** [comment]
> Huh, not sure why its not showing up for you guys. I just ran it all again and it was looking fine. All I can think of is the environment file, but if anyone has any other ideas let me know.
> 
> This is what its supposed to look like: Screenshot 2024-04-12 at 10 19 15 PM

Is it a render problem? cuz I tried to see your part via the link the render bot generate automatically.

**Comment by meretelutz** [comment]
OOooooh yes I think it is! Just clicked on that link and it isn't showing up for me either. I'm curious if that link is tied to an older commit, so I'm going to close this pull request and open another one and see if it shows up then.

**Pull request closed without merging**
