### PR TITLE
update app.py to add region centers dict

### LINKED ISSUE #77: Center worldwide distribution on selected region

### LINKED ISSUE #81: Center map and highlight bar chart

### PR DESCRIPTION
**Pull request by killerninja8**
Closes #81
Closes #77

### CODE REVIEW

**Review by meretelutz — CHANGES_REQUESTED** [review]
Love this new map! This projection is great! 

It looks really good, but I think the region centers might need a little work. Right now when you select a continent it zooms in really far and you have to zoom out to get a general idea of what is going on in that continent. So might be a good idea to tweak the zoom and center a bit more so that we get a better sense of the continent as a whole.

**Comment by killerninja8** [comment]
Ah I see! I can change the zoom scale to 2x instead of 4x so it's clearly visible.

**Comment by killerninja8** [comment]
resolved merge conflict

**Review by meretelutz — APPROVED** [review]
Looks great now, thanks for fixing!

**Pull request merged**
