### PR TITLE
Update callbacks.py to limit to 4 countries

### LINKED ISSUE #133: Limit the number of selections.

### PR DESCRIPTION
**Pull request by killerninja8**
Closes #133

### CODE REVIEW

**Comment by meretelutz** [comment]
Playing around with this now. I don't love that we can still select as many countries as we want with the filter. I'm trying out a dmc.MultiSelect from Dash Mantine Components, which you can set maxSelectedValues with, but now the other filters aren't working as expected.

**Comment by meretelutz** [comment]
This is what I was trying out:
`unique_countries = data['countryname'].unique()
    country_filter = html.Div([
        html.Label('Select countries:'),
        dmc.MultiSelect(
            id='country_filter',
            data=[{"label": country, "value": country} for country in unique_countries],
            placeholder='Select up to 3 countries...',
            maxSelectedValues=3,
            searchable=True
        )
    ])`

I couldn't get the filter choices to reflec the options from previous filters, so abandoning this for now.

**Comment by killerninja8** [comment]
Oh cool! It'd be great if we could work with that but it seems like it isn't a built-in solution yet. This is what I could find: https://community.plotly.com/t/dash-multi-dropdown-menu-limit/7921/3

**Review by meretelutz — APPROVED** [review]
I think this is a good fix for now! There doesn't seem to be a way to limit number of selections without switching the filter over to a dmc.MultiSelect, which we would then have to change the regional filter to as well. This is too big of a change for this milestone, so we'll settle for this change now!

**Comment by meretelutz** [comment]
@killerninja8 Yes! I was reading the same post hahaha. Like I said above, it would be nice if we could switch over to the dmc option but I don't think we have time this week.

**Pull request merged**
